teambuilderapp/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('players/', views.player_index, name='player-index'),
    path('players/<int:player_id>/', views.player_detail, name='player-detail'),
    path('players/create/', views.PlayerCreate.as_view(), name='player-create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='player-update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='player-delete'),
    path('rating/create', views.RatingCreate.as_view(), name='rating-create'),
    path('rating/<int:pk>/', views.RatingDetail.as_view(), name='rating-detail'),
    path('rating/', views.RatingList.as_view(), name='rating-index'),
    path('rating/<int:pk>/update/', views.RatingUpdate.as_view(), name='rating-update'),
    path('rating/<int:pk>/delete/', views.RatingDelete.as_view(), name='rating-delete'),
    path('rating/<int:pk>/associate-rating/<int:rating_id>/', views.associate_rating, name='associate-rating'),
    path('accounts/signup/', views.signup, name='signup'),
]

teambuilderapp/teambuilderapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teambuilderapp/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
# Import the User
from django.contrib.auth.models import User
# Create your models here.
class Team(models.Model):
    name = models.CharField(max_length=100)
    team = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()

    def __str__(self):
        return self.name

class Rating(models.Model):
    rating = models.CharField(max_length=200)
    sell = models.CharField(max_length=50)
    
    def __str__(self):
        return self.rating
    def get_absolute_url(self):
        return reverse("rating-detail", kwargs={"pk": self.id})        
class Player(models.Model):
    name = models.CharField(max_length=100)
    team = models.CharField(max_length=100)
    STRIKER = "ST"
    LEFT_WING = "LW"
    RIGHT_WING = "RW"
    ATTACKING_MIDFIELDER = "AM"
    DEFENSIVE_MIDFIELDER = "DM"
    LEFT_BACK = "LB"
    CENTER_BACK = "CB"
    RIGHT_BACK = "RB"
    GOAL_KEEPER = "GK"
    PLAYER_POSITION_CHOICES = {
        "ST": "Striker",
        "LW": "Left Wing",
        "RW": "Right Wing",
        "AM": "Attacking Midfielder",
        "DM": "Defensive Midfielder",
        "LB": "Left Back",
        "CB": "Center Back",
        "RB": "Right Back",
        "GK": "Goal Keeper",
    }
    player_position = models.CharField(
        max_length=2,
        choices=PLAYER_POSITION_CHOICES,
        default=STRIKER,
    )
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    profile_image = models.ImageField(upload_to='images/player_images/', blank=True, null=True)
    rating = models.ManyToManyField(Rating)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name
    
    def is_attacker(self):
        return self.player_position in {self.STRIKER, self.LEFT_WING, self.RIGHT_WING}
    
    def is_midfielder(self):
        return self.player_position in {self.ATTACKING_MIDFIELDER, self.DEFENSIVE_MIDFIELDER}
    
    def is_defender(self):
        return self.player_position in {self.RIGHT_BACK, self.LEFT_BACK, self.CENTER_BACK}
    def is_goalkeeper(self):
        return self.player_position in {self.GOAL_KEEPER}
    
    def get_absolute_url(self):
        return reverse('player-detail', kwargs={'player_id': self.id})

TROPHIES =(
    ('EPL', 'English Premier League'),
    ('UCL', 'UEFA Champions League'),
    ('FAC', 'Footballers Association Cup'),
    ('NON','No Trophies won this season!'),
    )
class Trophy(models.Model):
    # date = models.DateField('Trophy Date')
    trophy = models.CharField(
        max_length=3,
        choices = TROPHIES,
        default=TROPHIES[3][0]
    )
    
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_trophy_display()}"
    

    

teambuilderapp/main_app/forms.py
from django import forms
from .models import Trophy

class TrophyForm(forms.ModelForm):
    class Meta:
        model = Trophy
        fields = ('trophy',)

teambuilderapp/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Player, Rating
from .forms import TrophyForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class Home(LoginView):
    template_name = 'home.html'

@login_required
def player_index(request):
    players = Player.objects.filter(user=request.user)
    return render(request, 'player_index.html', {'players': players})

@login_required
def player_detail(request, player_id):
    player = Player.objects.get(id=player_id)
    rating = Rating.objects.all()
    trophy_form = TrophyForm()
    return render(request, 'player/detail.html', {'player': player, 'trophy_form': trophy_form, 'rating':rating })

class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    fields = ['name', 'team', 'player_position', 'description', 'age', 'profile_image', 'rating']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
class PlayerUpdate(LoginRequiredMixin, UpdateView):
    model = Player
    fields = ['name', 'team', 'player_position', 'description', 'age', 'profile_image', 'rating']

class PlayerDelete(LoginRequiredMixin, DeleteView):
    model = Player
    success_url = '/players/'
    
class RatingCreate(LoginRequiredMixin, CreateView):
    model = Rating
    fields = '__all__'
    
class RatingList(LoginRequiredMixin, ListView):
    model = Rating
    
class RatingDetail(LoginRequiredMixin, DetailView):
    model = Rating
    
class RatingUpdate(LoginRequiredMixin, UpdateView):
    model = Rating
    fields = '__all__'
    
class RatingDelete(LoginRequiredMixin, DeleteView):
    model = Rating
    success_url = '/rating/'
    
def associate_rating(request, player_id, rating_id):
    Player.objects.get(id=player_id).rating.add(rating_id)
    return redirect('player-detail', player_id=player_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('player-index')
        else:
            error_message = 'Invalid sign up - try again'
    form =UserCreationForm()
    context = {'form':form, 'error_message':error_message}
    return render(request, 'signup.html', context)

teambuilderapp/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Team Builder</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img src="" alt="The Team Builder Logo" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="/players">Players</a></li>
            <li><a href="{% url 'player-create' %}">Add a player</a></li>
            <li><a href="{% url 'rating-create' %}">Add a rating</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

teambuilderapp/main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<section class="logo-container">
    <div class="player-container">
        <img src="" alt="">
    </div>
    <img src="" alt="">
</section>
{% if not user.is_authenticated %}
<section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
</section>
{% endif %}
{% endblock %}

teambuilderapp/main_app/templates/index.html
{% extends 'base.html' %} 
{% block content %}
   <h1>Index for team builder</h1> 
{% endblock %}

teambuilderapp/main_app/templates/main_app/player_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}
<div class="page-header">
    <h1>Delete Player?</h1>
</div>

<h2>Are you sure you want to delete {{ player.name }}</h2>

<form action="" method="post" class="form">
    {% csrf_token %}
    <a href="{% url 'player-detail' player.id %}" class="btn secondary">Cancel</a>
    <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

teambuilderapp/main_app/templates/main_app/player_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}

<form action="" method="post" enctype="multipart/form-data" class="form-container">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

teambuilderapp/main_app/templates/main_app/rating_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Rating?</h1>
  {% comment %} <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" /> {% endcomment %}
</div>
<h2>Are you sure you want to delete this review?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'rating-detail' rating.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

teambuilderapp/main_app/templates/main_app/rating_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
{% comment %} <link rel="stylesheet" href="{% static 'css/toys/toy-detail.css' %}" /> {% endcomment %}
{% endblock %} 
{% block content %}

<div class="card" style="border-color: {{ toy.color }}">
  <div class="card-bg" style="background-color: {{ toy.color }}"></div>
  <div class="card-content">
    <h2>{{ rating.sell }}</h2>
    <p>{{ rating.rating }}</p>
  </div>
</div>
<a href="{% url 'rating-update' rating.id %}" class="btn warn">Edit</a>
<a href="{% url 'rating-delete' rating.id %}" class="btn danger">Delete</a>

{% endblock %}

teambuilderapp/main_app/templates/main_app/rating_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add a Rating</h1>
    {% endif %}
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

teambuilderapp/main_app/templates/main_app/rating_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
{% comment %} <link rel="stylesheet" href="{% static 'css/toys/toy-index.css' %}" /> {% endcomment %}
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Ratings</h1>
  {% comment %} <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
  <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
  <img src="{% static 'images/post.svg' %}" alt="A scratching post" />
  <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" /> {% endcomment %}
</section>

<section class="card-container">
  {% for rating in rating_list %}
    <div class="card" style="border-color: {{ toy.color }}">
      <div class="card-bg" style="background-color: {{ toy.color }}"></div>
      <a href="{% url 'rating-detail' rating.id %}">
        <div class="card-content">
          <h2>{{ rating.sell }}</h2>
          <p>{{ rating.rating }}</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

teambuilderapp/main_app/templates/player/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
{% endblock %} 
{% block content %}

<section class="player-container">
    <div class="player-img">
    </div>
    <div class="player-details">
        <h1>{{ player.name }}</h1>
        <h3>{{ player.team }}</h3>
        <h3>{{ player.player_position }}</h3>
        <h3>{{ player.age }}</h3>
        <p>{{ player.description }}</p>
        {% for trophy in player.trophy_set.all %}
            <p>{{ trophy.get_trophy_display }}</p>
        {% endfor %}
    </div>
    <div class="player-actions">
        <a href="{% url 'player-update' player.id %}" class="btn warn">Edit</a>
        <a href="{% url 'player-delete' player.id %}" class="btn danger">Delete</a>
    </div>
</section>
{% endblock %}

teambuilderapp/main_app/templates/player_index.html
{% extends 'base.html' %} 
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
{% endblock %}
{% block content %}

<section class="page-header">
    <h1>Index for players</h1> 
</section>
<section class="card-container">
    {% for player in players %}
    <div class="card">
        <a href="/players/{{ player.id }}">
        <div class="card-content">
            <h2 class="card-title">{{ player.name }}</h2>
            <div class="card-img-container">
                {% if player.profile_image %}
                    <img src="{{ player.profile_image.url }}" alt="{{ player.name }}" class="card-img">
                {% else %}
                    <img src="{% static 'images/No_Image_Available.jpg' %}" alt="No Imagae Available" class="card-img">
                {% endif %}
            </div>
            <h2 class="card-team">{{ player.team }}</h2>
            <p>{{ player.player_position }}</p>
            <p>{{ player.age }}</p>
            <p>{{ player.description }}</p>
        </div>
        </a>
    </div>
    {% endfor %}
</section>
{% endblock %}

teambuilderapp/main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}